### ISSUE TITLE
In docker the facebook video call crashes app

### ISSUE THREAD

**Issue by magicalbob** [magicalbob/ctime#1]
When video call button pressed get this stack trace:

`Traceback (most recent call last):
  File "./ctime.py", line 484, in <module>
    THE_GAME.check_event(e, pos)
  File "./ctime.py", line 374, in check_event
    self.click_facebook()
  File "./ctime.py", line 331, in click_facebook
    self.facebook.make_call()
  File "/opt/ctime/ctime_facebook.py", line 99, in make_call
    self.driver.switch_to_window(new_win)
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/webdriver.py", line 782, in switch_to_window
    self._switch_to.window(window_name)
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/switch_to.py", line 112, in window
    self._w3c_window(window_name)
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/switch_to.py", line 123, in _w3c_window
    send_handle(window_name)
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/switch_to.py", line 119, in send_handle
    self._driver.execute(Command.SWITCH_TO_WINDOW, {'handle': h})
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidArgumentException: Message: Expected "handle" to be a string, got [object Undefined] undefined
`

Work fine natively in linux. Only throws this in the docker container.

**Comment by magicalbob** [comment]
Launching the docker container with `--entrypoint bash` the app successfully launches firefox browser and connects to facebook. When I manually launch a video chat from that browser it displays: ```
Couldn't connect to your camera or microphone
Your camera or microphone are either not connected or not supported. For troubleshooting suggestions and information on supported browsers, visit our Help Centre.
```

Suggests it might be missing some dependencies?

**Comment by magicalbob** [comment]
I've moved the Dockerfile to use centos instead of ubuntu. Firefox still complains about mic/camera not being detected (camera works in the ctime_camera.py module) and the app launches a window for the chat but it timesout .... but the python doesn't complain and goes in to the game loop for in call.
